INSERT INTO `case_study_furama`.`rent_type` ( `rent_name`) VALUES ( 'Năm');
INSERT INTO `case_study_furama`.`rent_type` (`rent_name`) VALUES ('Tháng');
INSERT INTO `case_study_furama`.`rent_type` (`rent_name`) VALUES ('Ngày');
INSERT INTO `case_study_furama`.`rent_type` (`rent_name`) VALUES ('Giờ');

INSERT INTO education_degree (edu_name) values 
('Trung cấp') ,
('Cao đẳng') ,
('Đại học ') ,
('sau đại học') ;

INSERT INTO position (pos_name) values 
('Lễ tân') ,
('phục vụ') ,
('chuyên viên') ,
('giám sát'),
('quản lý'),
('giám đốc');

INSERT INTO division (division_name) values 
('Sale – Marketing') ,
('Hành Chính') ,
('Phục vụ') ,
('Quản lý');

INSERT INTO customer_type (customer_type_name) values 
('Diamond') ,
('Platinium') ,
('Gold') ,
('Silver') ,
('Member');

insert into service_type (service_type_name) VALUES
('Villa'),( 'House'), ('Room' );

insert into attach_service (attach_name,attach_cost,attach_unit) VALUES
('massage',100,50),
( 'karaoke',50,50),
( 'thức ăn',40,50),
( 'Thức uống',40,50),
( 'thuê xe',30,50);

INSERT INTO `case_study_furama`.`role` (`role_id`, `role_name`) VALUES ('1', 'ROLE_ADMIN');
INSERT INTO `case_study_furama`.`role` (`role_id`, `role_name`) VALUES ('2', 'ROLE_EMPLOYEE');
INSERT INTO `case_study_furama`.`role` (`role_id`, `role_name`) VALUES ('3', 'ROLE_USER');

INSERT INTO `case_study_furama`.`user` (`username`, `is_disable`, `password`, `employee_id_employee_id`) VALUES ('admin', 0, '$2a$10$g7BfZY41rMKy5PIsksBIGe76/icUVQ1ddRdepEnZTdCJaSzm9JMSW', '1');
INSERT INTO `case_study_furama`.`user` (`username`, `is_disable`, `password`, `employee_id_employee_id`) VALUES ('user', 0, '$2a$10$g7BfZY41rMKy5PIsksBIGe76/icUVQ1ddRdepEnZTdCJaSzm9JMSW', '2');
INSERT INTO `case_study_furama`.`user` (`username`, `is_disable`, `password`, `employee_id_employee_id`) VALUES ('employee', 0, '$2a$10$g7BfZY41rMKy5PIsksBIGe76/icUVQ1ddRdepEnZTdCJaSzm9JMSW', '3');

INSERT INTO `case_study_furama`.`user_role` (`role_id`, `user_name`) VALUES ('1', '1');


INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '1', '0123456789', 'Mùa Bông Rớt', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lạnh Hoài', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Teemo', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '1');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '2');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Linh Dương Nan Ngọc', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Võ Sĩ Quyền Năng', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Võ Sĩ Quyền Năng', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Võ Sĩ Quyền Năng', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Võ Sĩ Quyền Năng', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Võ Sĩ Quyền Năng', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Võ Sĩ Quyền Năng', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Võ Sĩ Quyền Năng', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Võ Sĩ Quyền Năng', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '3');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Triệu Mây', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '5');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '4');
INSERT INTO `case_study_furama`.`customer` (`customer_adress`, `customer_birthday`, `customer_code`, `customer_email`, `customer_gender`, `customer_id_card`, `customer_name`, `customer_phone`, `customer_type_customer_type_id`) VALUES ('Thái Bình', '2000-01-02', 'KH-1234', 'tb@gmail.com', '2', '0123456789', 'Lộc Phú Hộ', '0901265897', '4');
